version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: product-service-server
    ports:
      - "50053:50053"
    env_file:
      - .env
    volumes:
      - ./server:/app
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: product-service-client
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ./client:/app
